spring:
  datasource:
    url: jdbc:h2:mem:storedb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: sa
      password: "{noop}sa"

server:
  port: 8080
